# Generated by Django 4.0.9 on 2023-02-14 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postReview', models.TextField()),
                ('postPublishDateTime', models.DateTimeField(auto_now_add=True)),
                ('postRatingDelicious', models.FloatField(error_messages={'blank': 'Please provide a rating from 1 to 5'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('postRatingEatAgain', models.FloatField(error_messages={'blank': 'Please provide a rating from 1 to 5'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('postRatingWorthIt', models.FloatField(error_messages={'blank': 'Please provide a rating from 1 to 5'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dishId', models.CharField(blank=True, max_length=255)),
                ('userId', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
