# Generated by Django 4.0.10 on 2023-02-18 02:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'Phone number already exists.'}, max_length=128, null=True, region=None, unique=True),
        ),
    ]
