# Generated by Django 4.0.10 on 2023-02-18 02:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
