# Generated by Django 4.0.10 on 2023-02-19 16:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postPhotoUrl',
            field=models.ImageField(null=True, upload_to=core.models.post_image_file_path),
        ),
    ]
