# Generated by Django 4.0.10 on 2023-03-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_post_postdishvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postPhotoUrl',
            new_name='postPhoto',
        ),
    ]
