# Generated by Django 4.0.10 on 2023-03-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_post_dishid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userId',
        ),
    ]
