# Generated by Django 4.0.10 on 2023-03-14 00:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_user_useraccountregisterdate_user_userbio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='user',
            name='userProfilePictureUrl',
            field=models.ImageField(null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
