# Generated by Django 4.0.10 on 2023-03-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_name_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='userEmailAddress',
        ),
    ]
