# Generated by Django 4.0.10 on 2023-03-14 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_email_user_useremailaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userUsername',
        ),
    ]
