# Generated by Django 4.0.10 on 2023-03-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_username_user_userusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postPublishIpAddress',
        ),
    ]
