# Generated by Django 4.0.10 on 2023-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_post_postpublishipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postPublishIpAddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
