# Generated by Django 4.0.10 on 2023-03-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_post_postpublishipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(blank=True, max_length=255)),
                ('dishPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dishIngredient', models.TextField(blank=True)),
                ('dishNutrition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=255)),
                ('sellerOperatingLocation', models.CharField(max_length=255)),
                ('sellerOperatingTime', models.JSONField(blank=True, null=True)),
                ('sellerVerified', models.BooleanField(default=False)),
                ('sellerSafeFood', models.BooleanField(default=False)),
                ('sellerHalal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
