# Generated by Django 4.0.10 on 2023-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_dish_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
