# Generated by Django 4.0.10 on 2023-03-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_dish_dishprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishInfoContributor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dish',
            name='dishMainIngredient',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='postId',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='sellerId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
