# Generated by Django 4.0.10 on 2023-04-28 05:59

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_user_userage_user_userfollowers_user_userfollowing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='sellerName',
            new_name='sellerBusinessName',
        ),
        migrations.AddField(
            model_name='seller',
            name='dishId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='sellerInfoContributor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='sellerOwnerId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='postLike',
        ),
        migrations.AddField(
            model_name='post',
            name='postLike',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellerOperatingLocation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellerOperatingTime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhoneNumber',
            field=core.models.NullablePhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
