# Generated by Django 4.0.10 on 2023-04-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_sellername_seller_sellerbusinessname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='sellerOperatingTime',
        ),
    ]
