# Generated by Django 4.0.10 on 2023-04-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_seller_selleroperatingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='sellerOperatingTime',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
