# Generated by Django 4.0.10 on 2023-04-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_seller_selleroperatingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='dishId',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sellerOwnerId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
