# Generated by Django 4.0.10 on 2023-05-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_seller_dishid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='postId',
        ),
    ]
