# Generated by Django 4.0.10 on 2023-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_user_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userShowBirthDate',
            field=models.BooleanField(default=True),
        ),
    ]
