# Generated by Django 4.0.10 on 2023-05-22 13:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_user_usershowbirthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userCoverPictureUrl',
            field=models.ImageField(null=True, upload_to=core.models.user_cover_picture_file_path),
        ),
    ]
