# Generated by Django 4.0.10 on 2023-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_user_userfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IPv4',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
