# Generated by Django 4.0.10 on 2023-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_user_ipv4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IPv4',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
