# Generated by Django 4.0.10 on 2023-05-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_user_ipv4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userFriends',
            new_name='userFriend',
        ),
    ]
