# Generated by Django 4.0.10 on 2023-06-02 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_rename_userfriends_user_userfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postLike',
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('likeDateTime', models.DateTimeField(auto_now_add=True)),
                ('likeIpAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('likeUserAgent', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
