# Generated by Django 4.0.10 on 2023-06-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_menuitem_deliciousrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='postRatingDelicious',
            new_name='eatAgainRating',
        ),
    ]
