# Generated by Django 4.0.10 on 2023-06-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_rename_postratingdelicious_menuitem_eatagainrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dishId',
            new_name='menuItemId',
        ),
    ]
