# Generated by Django 4.0.10 on 2023-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_rename_dishid_post_menuitemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postLikeCount',
            field=models.IntegerField(default=0),
        ),
    ]
