# Generated by Django 4.0.10 on 2023-06-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_post_postlikecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='dishId',
            new_name='menuItemId',
        ),
    ]
