# Generated by Django 4.0.10 on 2023-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_menuitem_deliciousrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
