# Generated by Django 4.0.10 on 2023-09-05 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharedDateTime', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('sharedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_post', to=settings.AUTH_USER_MODEL)),
                ('sharedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
