# Generated by Django 4.0.10 on 2023-09-06 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_postshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='businessId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('businessOperatingLocation', models.JSONField(blank=True, null=True)),
                ('businessOperatingTime', models.JSONField(blank=True, null=True)),
                ('businessVerified', models.BooleanField(default=False)),
                ('businessSafeFood', models.BooleanField(default=False)),
                ('businessHalal', models.BooleanField(default=False)),
                ('businessOwnerId', models.IntegerField(blank=True, null=True)),
                ('businessInfoContributor', models.JSONField(blank=True, null=True)),
                ('menuItemId', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
