# Generated by Django 4.0.10 on 2023-09-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_rename_comment_postcomment_commentcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.business'),
        ),
    ]
