# Generated by Django 4.0.10 on 2023-09-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_menuitem_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sellerId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
