# Generated by Django 4.0.10 on 2023-09-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_rename_comment_postcomment_commentcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='commentReplises',
            new_name='commentReplies',
        ),
    ]
