# Generated by Django 4.0.10 on 2023-09-15 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_rename_commentreplises_postcomment_commentreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='commentLikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('likeDateTime', models.DateTimeField(auto_now_add=True)),
                ('likeIpAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('likeUserAgent', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
