# Generated by Django 4.0.10 on 2023-09-17 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_postcomment_commentlikecount_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='commentPublishLocation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
