# Generated by Django 4.0.10 on 2023-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_business_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='businessTrendRanking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
