# Generated by Django 4.0.10 on 2023-09-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_business_businesstrendranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='businessId',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='totalPostCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='menuItemId',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.business'),
        ),
        migrations.AddField(
            model_name='post',
            name='menuItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.menuitem'),
        ),
    ]
