# Generated by Django 4.0.10 on 2023-09-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_remove_menuitem_businessid_remove_menuitem_postid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='menuItemId',
        ),
    ]
